modLoader="javafml"
loaderVersion="[30,)"

[[mods]]
modId="torchbowmod"
version="${file.jarVersion}"
displayName="TorchBowMod"
updateJSONURL="https://raw.githubusercontent.com/noriokun4649/TorchBowMod/master/update.json"
credits="noriokun4649"
authors="noriokun4649"
description="Adds a TorchBow."

[[dependencies.torchbowmod]]
    modId="forge"
    mandatory=true
    versionRange="[30,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.torchbowmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.1,1.15.2]"
    ordering="NONE"
    side="BOTH"